import React from 'react'
import Head from 'next/head'
import Slider from '../components/slider/Slider'
import Container from '@/layout/Container'
import { Title } from '@/components/interface/Title'
import Link from 'next/link'
import SquareCar from '@/components/interface/cards/SquareCar'
import { Grid06 } from '@/layout/Grid'
import Image from 'next/image'
import { getSlides } from '@/functions/requests/slide/slideRequests'
import { InferGetStaticPropsType } from 'next'
import { FadeLoader } from 'react-spinners'
import CardCar from '@/components/interface/cards/CardCar'
import ProdutoRequest from '@/functions/requests/produto/produtoRequest'

const categorias = [
  { nome: 'todos' },
  { nome: 'sedan' },
  { nome: 'hatch' },
  { nome: 'suv' },
  { nome: 'pick-up' },
  { nome: 'minivan' },
  { nome: 'esportivo' }
]

const request = new ProdutoRequest(`${process.env.NEXT_API_URL}/api/produtos`)

export async function getStaticProps() {
  const slides = await getSlides();
  const carros = await request.getRequest();
  return {
    props: {
      slides,
      carros
    }
  }
}

export default function Home({slides, carros}:InferGetStaticPropsType<typeof getStaticProps>) {
  
  const [_carros, setCarros] = React.useState<DataGridCar[] | undefined | null>(carros)
  const [active, setActive] = React.useState<string>('todos')  
 
  const override = {
    display: 'block',
    margin: '200px auto',
    borderColor: 'red',
  }

  function Loading() {
    return (
      <div className="sweet-loading">
        <FadeLoader color={"#123abc"} loading={true} cssOverride={override}/>
      </div>
    );
  }

  function handleClick({currentTarget}:React.MouseEvent) {    
    if (currentTarget instanceof HTMLLIElement) {                
      setActive(currentTarget.innerText)
      if (carros) {               
        if (currentTarget.innerText !== "todos") {          
          setCarros( () => carros.filter( (carro) => {
              return carro.categoria === currentTarget.innerText
            })
          )
        } else {
          setCarros(carros)
        }
      } else {
        console.log('error')
      }
    }
  }

  function render() {
    if(_carros){
      return _carros.map( (carro, index) => {        
        return (
          <CardCar
            src={carro.image as string}
            alt={`${carro.marca} - ${carro.modelo}`}
            ano={carro.ano} 
            key={index}            
            marca={carro.marca}
            modelo={carro.modelo}
            href={`/${carro.categoria}/${carro.id}`}            
          />
        )
      })
    } else {
      return <div>{Loading()}</div>
    }
  }
  
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>

      {(slides)? <Slider slides={slides}/> : <div>{Loading()}</div>}
      
      <div>        
        <section>
          <div className="title-catalogo">
            <span>Escolha a categoria</span>
          </div>
          <div>
            <ul className='categoria-btn'>
              {categorias.map( (categoria, index) => {
                return (
                  <li 
                  key={index} 
                  className={(categoria.nome === active) ? "active" : ""}
                  onClick={handleClick}                  
                  >
                    <span>{categoria.nome}</span>
                  </li>
                )
              })}
            </ul>
          </div>
        </section>
        <section>
          <Container className="wrap">
            {render()}
          </Container>
        </section>
      </div>

      <section className="principal">
        <Title text="Lorem Ipsum is simply dummy text of the printing and typesetting industry." />
        <Container>
        <SquareCar
          src={'/sw4.png'}
          width={580}
          height={420}
          alt="Carro sw4"
          texto={'toyota sw4'}          
        />
        <SquareCar
          src={'/hilux.png'}
          width={580}
          height={420}
          alt="Carro hilux"
          texto={'toyota hilux'}
        />
        </Container>
        <div className="content-button">
          <Link href="/" legacyBehavior>
            <a className="btn">confira nosso estoque</a>
          </Link>
        </div>
      </section>

      <section className="assistencia">
        <Container className="wrap">
          <Grid06>
            <div className="info">
              <h2>Lorem Ipsum</h2>
              <p>
              Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
              </p>
              <Link href="/" legacyBehavior>
                <a>saiba mais +</a>
              </Link>
            </div>
          </Grid06>
          <Grid06>
            <Image
              src="/assistencia.jpg"
              width={580}
              height={460}
              alt="mulher callcenter - atendimento assistencia"
              style={{width:"100%", objectFit:"contain"}}
            />
          </Grid06>
        </Container>
      </section>
    </>
  )  
}
